-- Carga masiva de paises para pryFitLife
START TRANSACTION;

INSERT INTO paises (nombre, cod_postal)
VALUES
('Afghanistan', 'AFG'),
('Aland Islands', 'ALA'),
('Albania', 'ALB'),
('Algeria', 'DZA'),
('American Samoa', 'ASM'),
('Andorra', 'AND'),
('Angola', 'AGO'),
('Anguilla', 'AIA'),
('Antarctica', 'ATA'),
('Antigua and Barbuda', 'ATG'),
('Argentina', 'ARG'),
('Armenia', 'ARM'),
('Aruba', 'ABW'),
('Australia', 'AUS'),
('Austria', 'AUT'),
('Azerbaijan', 'AZE'),
('Bahrain', 'BHR'),
('Bangladesh', 'BGD'),
('Barbados', 'BRB'),
('Belarus', 'BLR'),
('Belgium', 'BEL'),
('Belize', 'BLZ'),
('Benin', 'BEN'),
('Bermuda', 'BMU'),
('Bhutan', 'BTN'),
('Bolivia', 'BOL'),
('Bonaire, Sint Eustatius and Saba', 'BES'),
('Bosnia and Herzegovina', 'BIH'),
('Botswana', 'BWA'),
('Bouvet Island', 'BVT'),
('Brazil', 'BRA'),
('British Indian Ocean Territory', 'IOT'),
('Brunei', 'BRN'),
('Bulgaria', 'BGR'),
('Burkina Faso', 'BFA'),
('Burundi', 'BDI'),
('Cambodia', 'KHM'),
('Cameroon', 'CMR'),
('Canada', 'CAN'),
('Cape Verde', 'CPV'),
('Cayman Islands', 'CYM'),
('Central African Republic', 'CAF'),
('Chad', 'TCD'),
('Chile', 'CHL'),
('China', 'CHN'),
('Christmas Island', 'CXR'),
('Cocos (Keeling) Islands', 'CCK'),
('Colombia', 'COL'),
('Comoros', 'COM'),
('Congo', 'COG'),
('Cook Islands', 'COK'),
('Costa Rica', 'CRI'),
('Croatia', 'HRV'),
('Cuba', 'CUB'),
('Curaçao', 'CUW'),
('Cyprus', 'CYP'),
('Czech Republic', 'CZE'),
('Democratic Republic of the Congo', 'COD'),
('Denmark', 'DNK'),
('Djibouti', 'DJI'),
('Dominica', 'DMA'),
('Dominican Republic', 'DOM'),
('Ecuador', 'ECU'),
('Egypt', 'EGY'),
('El Salvador', 'SLV'),
('Equatorial Guinea', 'GNQ'),
('Eritrea', 'ERI'),
('Estonia', 'EST'),
('Eswatini', 'SWZ'),
('Ethiopia', 'ETH'),
('Falkland Islands', 'FLK'),
('Faroe Islands', 'FRO'),
('Fiji Islands', 'FJI'),
('Finland', 'FIN'),
('France', 'FRA'),
('French Guiana', 'GUF'),
('French Polynesia', 'PYF'),
('French Southern Territories', 'ATF'),
('Gabon', 'GAB'),
('Georgia', 'GEO'),
('Germany', 'DEU'),
('Ghana', 'GHA'),
('Gibraltar', 'GIB'),
('Greece', 'GRC'),
('Greenland', 'GRL'),
('Grenada', 'GRD'),
('Guadeloupe', 'GLP'),
('Guam', 'GUM'),
('Guatemala', 'GTM'),
('Guernsey', 'GGY'),
('Guinea', 'GIN'),
('Guinea-Bissau', 'GNB'),
('Guyana', 'GUY'),
('Haiti', 'HTI'),
('Heard Island and McDonald Islands', 'HMD'),
('Honduras', 'HND'),
('Hong Kong S.A.R.', 'HKG'),
('Hungary', 'HUN'),
('Iceland', 'ISL'),
('India', 'IND'),
('Indonesia', 'IDN'),
('Iran', 'IRN'),
('Iraq', 'IRQ'),
('Ireland', 'IRL'),
('Israel', 'ISR'),
('Italy', 'ITA'),
('Ivory Coast', 'CIV'),
('Jamaica', 'JAM'),
('Japan', 'JPN'),
('Jersey', 'JEY'),
('Jordan', 'JOR'),
('Kazakhstan', 'KAZ'),
('Kenya', 'KEN'),
('Kiribati', 'KIR'),
('Kosovo', 'XKX'),
('Kuwait', 'KWT'),
('Kyrgyzstan', 'KGZ'),
('Laos', 'LAO'),
('Latvia', 'LVA'),
('Lebanon', 'LBN'),
('Lesotho', 'LSO'),
('Liberia', 'LBR'),
('Libya', 'LBY'),
('Liechtenstein', 'LIE'),
('Lithuania', 'LTU'),
('Luxembourg', 'LUX'),
('Macau S.A.R.', 'MAC'),
('Madagascar', 'MDG'),
('Malawi', 'MWI'),
('Malaysia', 'MYS'),
('Maldives', 'MDV'),
('Mali', 'MLI'),
('Malta', 'MLT'),
('Man (Isle of)', 'IMN'),
('Marshall Islands', 'MHL'),
('Martinique', 'MTQ'),
('Mauritania', 'MRT'),
('Mauritius', 'MUS'),
('Mayotte', 'MYT'),
('Mexico', 'MEX'),
('Micronesia', 'FSM'),
('Moldova', 'MDA'),
('Monaco', 'MCO'),
('Mongolia', 'MNG'),
('Montenegro', 'MNE'),
('Montserrat', 'MSR'),
('Morocco', 'MAR'),
('Mozambique', 'MOZ'),
('Myanmar', 'MMR'),
('Namibia', 'NAM'),
('Nauru', 'NRU'),
('Nepal', 'NPL'),
('Netherlands', 'NLD'),
('New Caledonia', 'NCL'),
('New Zealand', 'NZL'),
('Nicaragua', 'NIC'),
('Niger', 'NER'),
('Nigeria', 'NGA'),
('Niue', 'NIU'),
('Norfolk Island', 'NFK'),
('North Korea', 'PRK'),
('North Macedonia', 'MKD'),
('Northern Mariana Islands', 'MNP'),
('Norway', 'NOR'),
('Oman', 'OMN'),
('Pakistan', 'PAK'),
('Palau', 'PLW'),
('Palestinian Territory Occupied', 'PSE'),
('Panama', 'PAN'),
('Papua New Guinea', 'PNG'),
('Paraguay', 'PRY'),
('Peru', 'PER'),
('Philippines', 'PHL'),
('Pitcairn Island', 'PCN'),
('Poland', 'POL'),
('Portugal', 'PRT'),
('Puerto Rico', 'PRI'),
('Qatar', 'QAT'),
('Reunion', 'REU'),
('Romania', 'ROU'),
('Russia', 'RUS'),
('Rwanda', 'RWA'),
('Saint Helena', 'SHN'),
('Saint Kitts and Nevis', 'KNA'),
('Saint Lucia', 'LCA'),
('Saint Pierre and Miquelon', 'SPM'),
('Saint Vincent and the Grenadines', 'VCT'),
('Saint-Barthelemy', 'BLM'),
('Saint-Martin (French part)', 'MAF'),
('Samoa', 'WSM'),
('San Marino', 'SMR'),
('Sao Tome and Principe', 'STP'),
('Saudi Arabia', 'SAU'),
('Senegal', 'SEN'),
('Serbia', 'SRB'),
('Seychelles', 'SYC'),
('Sierra Leone', 'SLE'),
('Singapore', 'SGP'),
('Sint Maarten (Dutch part)', 'SXM'),
('Slovakia', 'SVK'),
('Slovenia', 'SVN'),
('Solomon Islands', 'SLB'),
('Somalia', 'SOM'),
('South Africa', 'ZAF'),
('South Georgia', 'SGS'),
('South Korea', 'KOR'),
('South Sudan', 'SSD'),
('Spain', 'ESP'),
('Sri Lanka', 'LKA'),
('Sudan', 'SDN'),
('Suriname', 'SUR'),
('Svalbard and Jan Mayen Islands', 'SJM'),
('Sweden', 'SWE'),
('Switzerland', 'CHE'),
('Syria', 'SYR'),
('Taiwan', 'TWN'),
('Tajikistan', 'TJK'),
('Tanzania', 'TZA'),
('Thailand', 'THA'),
('The Bahamas', 'BHS'),
('The Gambia', 'GMB'),
('Timor-Leste', 'TLS'),
('Togo', 'TGO'),
('Tokelau', 'TKL'),
('Tonga', 'TON'),
('Trinidad and Tobago', 'TTO'),
('Tunisia', 'TUN'),
('Turkey', 'TUR'),
('Turkmenistan', 'TKM'),
('Turks and Caicos Islands', 'TCA'),
('Tuvalu', 'TUV'),
('Uganda', 'UGA'),
('Ukraine', 'UKR'),
('United Arab Emirates', 'ARE'),
('United Kingdom', 'GBR'),
('United States', 'USA'),
('United States Minor Outlying Islands', 'UMI'),
('Uruguay', 'URY'),
('Uzbekistan', 'UZB'),
('Vanuatu', 'VUT'),
('Vatican City State (Holy See)', 'VAT'),
('Venezuela', 'VEN'),
('Vietnam', 'VNM'),
('Virgin Islands (British)', 'VGB'),
('Virgin Islands (US)', 'VIR'),
('Wallis and Futuna Islands', 'WLF'),
('Western Sahara', 'ESH'),
('Yemen', 'YEM'),
('Zambia', 'ZMB'),
('Zimbabwe', 'ZWE')
;

COMMIT;